<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pradeepkulal-PC" failures="8" tests="19" name="Login Test" time="102.24" errors="0" timestamp="2024-05-03T15:37:07 IST">
  <testcase classname="org.intuitiveapps.Kycee.TestComponents.BaseTest" name="@BeforeMethod launchApplication" time="2.313">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn&amp;apos;t exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: &amp;apos;PRADEEPKULAL-PC&amp;apos;, ip: &amp;apos;192.168.137.1&amp;apos;
Build info: version: &amp;apos;4.11.0&amp;apos;, revision: &amp;apos;040bc5406b&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.10&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}]}]">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'PRADEEPKULAL-PC', ip: '192.168.137.1'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}]}]
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:159)
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:51)
at org.intuitiveapps.Kycee.TestComponents.BaseTest.intializeBrowser(BaseTest.java:44)
at org.intuitiveapps.Kycee.TestComponents.BaseTest.launchApplication(BaseTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod launchApplication -->
  <testcase classname="org.intuitiveapps.Kycee.TestComponents.BaseTest" name="@AfterMethod tearDown" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.openqa.selenium.WebDriver.close()&amp;quot; because &amp;quot;this.driver&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.close()" because "this.driver" is null
at org.intuitiveapps.Kycee.TestComponents.BaseTest.tearDown(BaseTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithBlogger" time="2.305">
    <failure type="java.lang.AssertionError" message="expected [User logged in.] but found [Incorrect password.]">
      <![CDATA[java.lang.AssertionError: expected [User logged in.] but found [Incorrect password.]
at org.intuitiveapps.Kycee.Tests.LoginTest.loginWithBlogger(LoginTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWithBlogger -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithBusinessAdmin" time="1.487">
    <failure type="java.lang.AssertionError" message="expected [User logged in.] but found [Email not associated with an account.]">
      <![CDATA[java.lang.AssertionError: expected [User logged in.] but found [Email not associated with an account.]
at org.intuitiveapps.Kycee.Tests.LoginTest.loginWithBusinessAdmin(LoginTest.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWithBusinessAdmin -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithBusinessUser" time="1.496">
    <failure type="java.lang.AssertionError" message="expected [User logged in.] but found [Email not associated with an account.]">
      <![CDATA[java.lang.AssertionError: expected [User logged in.] but found [Email not associated with an account.]
at org.intuitiveapps.Kycee.Tests.LoginTest.loginWithBusinessUser(LoginTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWithBusinessUser -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithCustomer" time="1.541">
    <failure type="java.lang.AssertionError" message="expected [User logged in.] but found [Email not associated with an account.]">
      <![CDATA[java.lang.AssertionError: expected [User logged in.] but found [Email not associated with an account.]
at org.intuitiveapps.Kycee.Tests.LoginTest.loginWithCustomer(LoginTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWithCustomer -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithEmptyEmail" time="0.552"/>
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithEmptyPassword" time="1.428"/>
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInActiveUser" time="2.492">
    <skipped/>
  </testcase> <!-- loginWithInActiveUser -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInActiveUser" time="1.627">
    <skipped/>
  </testcase> <!-- loginWithInActiveUser -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInActiveUser" time="1.725">
    <failure type="java.lang.AssertionError" message="expected [This user has been inactive. Please contact support.] but found [Incorrect password.]">
      <![CDATA[java.lang.AssertionError: expected [This user has been inactive. Please contact support.] but found [Incorrect password.]
at org.intuitiveapps.Kycee.Tests.LoginTest.loginWithInActiveUser(LoginTest.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInActiveUser -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInTerminatedUser" time="11.978">
    <skipped/>
  </testcase> <!-- loginWithInTerminatedUser -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInTerminatedUser" time="1.294">
    <skipped/>
  </testcase> <!-- loginWithInTerminatedUser -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInTerminatedUser" time="2.039">
    <failure type="java.lang.AssertionError" message="expected [This user has been terminated. Please contact support.] but found [Email not associated with an account.]">
      <![CDATA[java.lang.AssertionError: expected [This user has been terminated. Please contact support.] but found [Email not associated with an account.]
at org.intuitiveapps.Kycee.Tests.LoginTest.loginWithInTerminatedUser(LoginTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInTerminatedUser -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInvalidEmail" time="2.422"/>
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInvalidEmailFormat" time="0.438"/>
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithInvalidPassword" time="1.675"/>
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="loginWithSuperAdmin" time="1.607">
    <failure type="java.lang.AssertionError" message="expected [User logged in.] but found [Incorrect password.]">
      <![CDATA[java.lang.AssertionError: expected [User logged in.] but found [Incorrect password.]
at org.intuitiveapps.Kycee.Tests.LoginTest.loginWithSuperAdmin(LoginTest.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWithSuperAdmin -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="navigationToForgotPasswordPage" time="0.433">
    <skipped/>
  </testcase> <!-- navigationToForgotPasswordPage -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="navigationToForgotPasswordPage" time="0.375">
    <skipped/>
  </testcase> <!-- navigationToForgotPasswordPage -->
  <testcase classname="org.intuitiveapps.Kycee.Tests.LoginTest" name="navigationToForgotPasswordPage" time="0.396">
    <failure type="java.lang.AssertionError" message="expected [Forgot Password] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [Forgot Password] but found [true]
at org.intuitiveapps.Kycee.Tests.LoginTest.navigationToForgotPasswordPage(LoginTest.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- navigationToForgotPasswordPage -->
</testsuite> <!-- Login Test -->
